apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: alpine-app
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  # annotations:
  #   argocd-image-updater.argoproj.io/image-list: myalias=ghcr.io/coutug/alpine:0.x
  #   argocd-image-updater.argoproj.io/write-back-method: git
  #   argocd-image-updater.argoproj.io/git-branch: main
  #   argocd-image-updater.argoproj.io/write-back-target: kustomization
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: alpine
  source:
    repoURL: https://github.com/coutug/argocd.git
    targetRevision: main
    path: alpine
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true