apiVersion: v1
kind: Service
metadata:
  name: substreams-sink-prometheus-service
  namespace: substreams-sink-prometheus
  labels:
    app: substreams-sink-prometheus
spec:
  type: NodePort
  ports:
    - port: 9102
      nodePort: 30002
      targetPort: 9102
      protocol: TCP
  selector:
    app: substreams-sink-prometheus