apiVersion: apps/v1
kind: Deployment
metadata:
  name: alpine-deployment
  namespace: alpine
  labels:
    app: alpine
spec:
  replicas: 1
  selector:
    matchLabels:
      app: alpine
  template:
    metadata:
      labels:
        app: alpine
    spec:
      containers:
      - name: alpine-container
        image: ghcr.io/coutug/alpine:0.0
        command: ["sleep", "infinity"]