apiVersion: v1
kind: Service
metadata:
  name: alpine-svc
  namespace: alpine
  labels:
    app: alpine
spec:
  type: NodePort
  selector:
    app: alpine
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
